DROP TABLE IF EXISTS CITIZEN_AADHAR;  
CREATE TABLE CITIZEN_AADHAR(  
aadharid INT   PRIMARY KEY, 
citizen_dob VARCHAR(10 ) NOT NULL , 
citizen_email  VARCHAR(25 ) NOT NULL,  
citzen_name VARCHAR(50) NOT NULL
);